import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import '../styles/globals.css';
import { ViewTransitions } from 'next-view-transitions';
import NextTopLoader from 'nextjs-toploader';
import { NextUIProvider } from '@nextui-org/react';
import Head from 'next/head';

const poppins = Poppins({ weight: ['400', '700'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Sparkathon',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Head>
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      </Head>
      <body className={poppins.className}>
        <NextTopLoader showSpinner={false} color='#036ffc' />
        <NextUIProvider>
          <ViewTransitions>{children}</ViewTransitions>
        </NextUIProvider>
      </body>
    </html>
  );
}
